// <auto-generated />
using System;
using CarDealership.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealership.DataAccess.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20250925091748_Initial_4_Tables")]
    partial class Initial_4_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CarDealership.DataAccess.Models.AvailableSku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureSet")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProductionYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelId");

                    b.ToTable("AvailableSku");
                });

            modelBuilder.Entity("CarDealership.DataAccess.Models.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarBrands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bmw"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lifan"
                        });
                });

            modelBuilder.Entity("CarDealership.DataAccess.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarModels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "BMW E30 M3"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "BMW X5"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "BMW X6"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Name = "BMW M1"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Name = "BMW M2"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "Mercedes-Benz GLE"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Name = "Mercedes-Benz S-Class"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Name = "Mercedes C-Class"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            Name = "Mercedes-AMG GT"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            Name = "Mercedes GLA-Class"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            Name = "Audi A3"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            Name = "Audi A5"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            Name = "Audi Q5"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            Name = "Audi Q3"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            Name = "Audi TT"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            Name = "Volkswagen Golf"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 4,
                            Name = "Volkswagen Passat"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 4,
                            Name = "Volkswagen Tiguan"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 4,
                            Name = "Volkswagen Jetta"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 4,
                            Name = "Volkswagen Touareg"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 5,
                            Name = "Peugeot 208 hatchback"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 5,
                            Name = "Peugeot 3008 SUV"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            Name = "Peugeot 206"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            Name = "Peugeot 3008"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 5,
                            Name = "Peugeot 308"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 6,
                            Name = "Toyota Camry"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 6,
                            Name = "Toyota Corolla"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 6,
                            Name = "Toyota RAV4"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 6,
                            Name = "Toyota Tundra"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 6,
                            Name = "Toyota Land Cruiser"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 6,
                            Name = "Toyota Tacoma"
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 6,
                            Name = "Toyota Prius"
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 7,
                            Name = "Nissan Note"
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 7,
                            Name = "Nissan Sunny"
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 7,
                            Name = "Nissan Skyline"
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 7,
                            Name = "Nissan Juke"
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 7,
                            Name = "Nissan Murano"
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 7,
                            Name = "Nissan Qashqai"
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 8,
                            Name = "Honda Accord"
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 8,
                            Name = "Honda Civic Hybrid"
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 8,
                            Name = "Honda CR-V"
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 8,
                            Name = "Honda Odyssey"
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 8,
                            Name = "Honda Prelude"
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 8,
                            Name = "Honda Integra"
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 9,
                            Name = "Lifan X60"
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 9,
                            Name = "Lifan X70"
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 9,
                            Name = "Lifan X80"
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 9,
                            Name = "Lifan 820"
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 9,
                            Name = "Lifan Maiwei"
                        });
                });

            modelBuilder.Entity("CarDealership.DataAccess.Models.SoldSku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureSet")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProductionYear")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SellingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelId");

                    b.ToTable("SoldSku");
                });

            modelBuilder.Entity("CarDealership.DataAccess.Models.AvailableSku", b =>
                {
                    b.HasOne("CarDealership.DataAccess.Models.CarBrand", "CarBrand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarDealership.DataAccess.Models.CarModel", "CarModel")
                        .WithMany("StockUnits")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarBrand");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("CarDealership.DataAccess.Models.CarModel", b =>
                {
                    b.HasOne("CarDealership.DataAccess.Models.CarBrand", "CarBrand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("CarDealership.DataAccess.Models.SoldSku", b =>
                {
                    b.HasOne("CarDealership.DataAccess.Models.CarBrand", "CarBrand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarDealership.DataAccess.Models.CarModel", "CarModel")
                        .WithMany("SoldUnits")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarBrand");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("CarDealership.DataAccess.Models.CarModel", b =>
                {
                    b.Navigation("SoldUnits");

                    b.Navigation("StockUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
